name: Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-latest, variant: msvc     }
          - { os: windows-latest, variant: mingw    }
          - { os: windows-latest, variant: clang-cl }
          - { os: macos-latest,   variant: metal    }
          - { os: macos-latest,   variant: vulkan   }
          - { os: ubuntu-latest,  variant: default  }

    steps:
      - uses: actions/checkout@v7

      - name: Install build dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt install xorg-dev autoconf autoconf-archive automake libtool libltdl-dev

      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows-latest' && (matrix.variant == 'msvc' || matrix.variant == 'clang-cl') }}

      - uses: stripe2933/http-cache-server@v0.1.0
        with:
         port: 12321

      - name: Configure CMake
        env:
          VCPKG_BINARY_SOURCES: "clear;http,http://localhost:12321/{name}-{version}-{sha},readwrite"
        run: |
          mv .github/workflows/scripts/* .
          cmake --preset=${{ matrix.os }}-${{ matrix.variant }}

      - name: Build
        run: cmake --build build --config Release

      - name: Upload binary executables
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-${{ matrix.variant }}-${{ github.sha }}
          path: |
            build/model-editor.exe
            build/model-editor.app
            build/model-editor
            build/*.dll